# Rust踩坑记录

> 草稿，之后会整理成博客



## 无法返回局部变量的引用

原因很简单：局部变量在作用域结束之后就会销毁，所以这个引用会成为 **野指针**。

解决办法：

1. 直接返回资源本身（最直接的办法）
2. 使用 `Box` 包装资源，同时返回该 `Box`
3. 使用智能指针包装，如 `Arc` / `Rc`

详情参见 http://bryce.fisher-fleig.org/blog/strategies-for-returning-references-in-rust/index.html



## 泛型trait Deserialize需要生命周期标识

举个例子

```rust
pub struct DiskStore<K, V>
    where
        K: ToArray,
        V: Serialize + Deserialize
{
    //....
}
```

这里就会报错。

解决办法：使用 `DeserializeOwned`  来获得所有权版本的 `trait`



## 使用 ? 运算符返回自定义错误

在 `rust` 中，`?` 的作用是 `unwrap` + 错误向上传递。

在很多时候，我们的 `Error` 是自定义的，但是 `?` 传递的 Error 并没法转成自定义的 Error。

为此，我们需要实现它们的 `From` trait。

```rust
impl From<std::io::Error> for StoreError {
    fn from(e: std::io::Error) -> Self {
        IOErr(e)
    }
}

impl From<Box<ErrorKind>> for StoreError {
    fn from(e: Box<ErrorKind>) -> Self {
        BinCodeErr(e)
    }
}

impl From<NoneError> for StoreError {
    fn from(_: NoneError) -> Self {
        NoneErr
    }
}
```

详情参见 https://lotabout.me/2017/rust-error-handling/



## 将 可变引用 转化为 非可变引用

```rust 
let mut tmp = String::from("2333"); // mutable reference
&*tmp // now it's immutable
```



## 对两个条件分支下，分别使用不可变应用和可变引用，borrow checker的报错

感觉是生命周期的问题

```rust
fn foo(x: &mut u8) -> Option<&u8> {
    if let Some(y) = bar(x) {
        return Some(y) // comment this out to calm compiler
    }
    bar(x)
}

fn bar(x: &mut u8) -> Option<&u8> { Some(x) }
```

报错：

```
error[E0499]: cannot borrow `*x` as mutable more than once at a time
 --> src/main.rs:7:9
  |
4 |     if let Some(y) = bar(x) {
  |                          - first mutable borrow occurs here
...
7 |     bar(x)
  |         ^ second mutable borrow occurs here
8 | }
  | - first borrow ends here
```



理论上 `bar(x)` 的生命周期应该在这个分支末尾就已经结束了，但是编译器还是认为 它在函数最后才会被销毁。

解决办法：使用 `polonius` 编译参数

`cargo rustc -- -Z polonius`